{"uuid": "fadb15f6-5ea8-4f70-b123-1807bb444735", "children": ["371af019-1c22-4e00-a5b6-e1ddfe3931f5"], "befores": [{"name": "_Class__pytest_setup_method", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73\n  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"D:\\softwore\\python372\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\fixtures.py\", line 778, in call_fixture_func\n    res = next(it)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\python.py\", line 773, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\python.py\", line 691, in _call_with_optional_argument\n    func()\n  File \"D:\\my-git-project\\91lng\\selenium_91lng_auto_test\\test_case\\test_bpm\\test_customer_manage.py\", line 19, in setup_method\n    self.customer_page = customer_manage_page.CustomerManagePage(add_base_login_data[\"base_data\"][3])\n  File \"D:\\my-git-project\\91lng\\selenium_91lng_auto_test\\common\\browser.py\", line 23, in __init__\n    self.driver = webdriver.Chrome(executable_path=CHROMEDRIVER_PATH)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1562682904832, "stop": 1562682908959}], "start": 1562682904832, "stop": 1562682909184}